import Image from "next/image";
import { Inter } from "next/font/google";
import Navbar from "@/components/core/navbar/Navbar";
import Head from "next/head";
import StartPage from "@/components/feature/StartPage";
import Works from "@/components/feature/works/Works";
import Contacts from "@/components/feature/contacts/Contacts";

export default function Home() {
  return (
    <>
      <Head>
        <title>TM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <StartPage />
        <Works />
        <Contacts />
      </main>
    </>
  );
}
